### ISSUE TITLE
WARNING on merging the same dict data

### ISSUE THREAD

**Issue by yeled** [leapfrogonline/ansible-merge-vars#22]
**Describe the Bug**
I get warning when the data in the {} is exactly the same. Even empty. This is the simplest bug report I could share.

I am using `ansible-merge-vars==3.0.0`, I tried `4.0.0` but it didn't change anything.

What am I doing wrong?

```
TASK [routing : Merge Aggregates] ****************************************************************************************************************************
task path: /Users/yeled/src/gh/network/ansible/roles/routing/tasks/main.yml:1
Friday 23 November 2018  12:52:57 +0000 (0:00:00.518)       0:00:10.563 *******
 [WARNING]: aggregates is already defined, are you sure you want to overwrite it?
The contents of aggregates are: {}
Merging vars in this order: []
ok: [leaf-1-lab.net.cp1-iad.github.net] => {
    "ansible_facts": {
        "aggregates": {}
    },
    "ansible_facts_cacheable": false,
    "changed": false
}
```

**Ansible Playbook**

```yaml
- name: Merge Aggregates
  merge_vars:
    suffix_to_merge: __aggregates__to_merge
    merged_var_name: aggregates
    expected_type: 'dict'
    recursive_dict_merge: yes
  when:
    - not unmerged_aggregates is defined


- name: "Routing Aggregates"
  template: src={{os}}/aggregates.j2 dest=../../tmp/fragments/{{inventory_hostname}}/aggregates.conf
  when:
    - aggregates is defined
    - inventory_hostname_short is match("bdr.*|!ssw.*|!spine.*")

- name: "Default VRF route"
  template: src={{os}}/default-vrf.j2 dest=../../tmp/fragments/{{inventory_hostname}}/iproute-default-vrf.conf
  when:
    - inventory_hostname_short is match("^leaf.*")
```

**Environment**
```
ansible 2.7.0
  config file = /Users/yeled/src/gh/network/ansible/etc/ansible.cfg
  configured module search path = [u'/Users/yeled/src/gh/network/ansible/env/lib/python2.7/site-packages/napalm_ansible']
  ansible python module location = /Users/yeled/src/gh/network/ansible/env/lib/python2.7/site-packages/ansible
  executable location = /Users/yeled/src/gh/network/ansible/env/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```
