### ISSUE TITLE
How this can be done with standard ansible

### ISSUE THREAD

**Issue by geraldh** [leapfrogonline/ansible-merge-vars#43]
Hello,
after revisiting the whole dict merge deprecation mess in ansible again - I think it's possible with the default "combine" ansible module by now - here's an example:
```
- name: mergedicts
  hosts: localhost
  vars:
    v0a_iptables__to_merge:
      a:
        x: default
        y: default
      b: default
      c: default
    v1a_iptables__to_merge:
      a:
        y: patch1
        z: patch1
      b: patch1
    v2a_iptables__to_merge:
      a:
        w: patch2
        z: patch2
      c: patch2

  tasks:
    - name: varnames iptables__to_merge
      ansible.builtin.debug:
        msg: "{{ lookup('vars', item) }}"
      loop: "{{ lookup('ansible.builtin.varnames', '.+iptables__to_merge$', wantlist=True) }}"

    - name: merge varnames with suffix iptables__to_merge
      set_fact:
        iptables_dict: "{{ iptables_dict | default({}) | ansible.builtin.combine(lookup('vars', item), recursive=True) }}"
      loop: "{{ lookup('ansible.builtin.varnames', '.+iptables__to_merge$', wantlist=True) }}"

    - name: iptables_dict
      ansible.builtin.debug: msg="{{ iptables_dict }}"
```
As the order of merging dicts is important - I use the convention:
- v0: group_vars
- v1: roles
- v2: host_vars

Run with ansible-playbook playbook_name.yaml
```
TASK [varnames iptables__to_merge] ********************************************************************************************
ok: [localhost] => (item=v0a_iptables__to_merge) => {
    "msg": {
        "a": {
            "x": "default",
            "y": "default"
        },
        "b": "default",
        "c": "default"
    }
}
ok: [localhost] => (item=v1a_iptables__to_merge) => {
    "msg": {
        "a": {
            "y": "patch1",
            "z": "patch1"
        },
        "b": "patch1"
    }
}
ok: [localhost] => (item=v2a_iptables__to_merge) => {
    "msg": {
        "a": {
            "w": "patch2",
            "z": "patch2"
        },
        "c": "patch2"
    }
}

TASK [merge varnames with suffix iptables__to_merge] **************************************************************************
ok: [localhost] => (item=v0a_iptables__to_merge)
ok: [localhost] => (item=v1a_iptables__to_merge)
ok: [localhost] => (item=v2a_iptables__to_merge)

TASK [iptables_dict] **************************************************************************************************
ok: [localhost] => {
    "msg": {
        "a": {
            "w": "patch2",
            "x": "default",
            "y": "patch1",
            "z": "patch2"
        },
        "b": "patch1",
        "c": "patch2"
    }
}
```
Anyway - thanks for the module - it has helped me a lot.

**Comment by fajpunk** [comment]
Ahh neat.  Will that work directly on lists?  I see it has options on how to handle list values within the dict, but it looks like `combine` still needs dicts as its initial arguments.  This is good to know though, and I'll put this strategy in the README.  Always better to not add a dependency if you don't have to!

**Comment by geraldh** [comment]
Hi,
yes - combine does not work with pure lists - I use instead:
```
- name: Merge local_groups_list                                                                                                                                                                                                            
  ansible.builtin.set_fact:                                                                                                                                                                                                                
    local_groups_list: "{{ local_groups_list | default([]) + lookup('vars', item) }}"                                                                                                                                                      
  loop: "{{ lookup('varnames', '.+local_groups__to_merge$', wantlist=True) }}"                                                                                                                                                             
  when: local_groups is not defined                                                                                                                                                                                                        

- name: Set local_groups
  ansible.builtin.set_fact:
    local_groups: "{{ local_groups_list | default([]) }}" 
  when: local_groups is not defined
```
The two-stage set_fact is necessary (also in the dict case), because, if the variable to be merged has the same name as the variable in the when clause, the loop is only executed once! - the ansible principle of maximum surprise ;) 

You can use the unique filter in the second set_fact to eliminate duplicates.
Merging a list of dictionaries will not merge the dicts.
